eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: projectA

debug: false
logging:
    config: classpath:log4j2-dev.xml
